name: DinguerieLoot
version: 1.0.0
description: Plugins aléatoire loot
author: BilalTeam
main: fr.bilal.dinguerie.DinguerieLoot
api-version: 1.20

commands:
  bilal:
    description: Commandes principales du plugin
    usage: /bilal <start|stop|evite|inclut|list>
    permission: bilal.admin
    permission-message: "§cVous n'avez pas la permission d'utiliser cette commande!"

permissions:
  bilal.admin:
    description: Permission pour utiliser les commandes du plugin
    default: op
